---
title: "MA7BY020 Syllabus"
---

<!-- [**Télécharger  "PDF du syllabus"**](/documents/MA7BY020-syllabus.pdf) -->


::: {.callout-note}

## Schedule

|           | Day       | Time              | Location                       |  Start |
|:---------:|:-----------:|:-------------------:|:--------------------------------|:--------|
| Lab session 1   | Wednesday  | 13:13-15:00  | [Somewhere](https://edt.math.univ-paris-diderot.fr/#/parcours/mathinfo/m1)      | 2025-01-15 |
| Lab session 2   | Friday  | 9:00-10:30  | Sophie Germain 2012      | 2024-01-17 |


### [ {{< fa cal >}} ](https://edt.math.univ-paris-diderot.fr/#/parcours/mathinfo/m1)

:::


::: {.callout-note}

### Organization  {{< fa chalkboard-teacher >}}{{< fa laptop-code >}}

We will have two weeky sessions of 1+1/2 hours each. Each session is organized around a [Lab](labs-listings.qmd). We will switch from blackboard to laptop and back. You are invited to bring your laptop to the lab sessions. 

{{< fa hand-point-right >}} We will not attempt to complete the labs during the sessions. You are expected to complete the labs on your own time. Solutions (at least partial solutions) are available on the course website.

You can fork the [course repository](https://github.com/s-v-b/MA7BY020) and post issues, comments, and corrections.



:::

::: {.callout-note}

## Objectives


{{< include _objectives_ma7BY020.qmd >}}

:::


::: {.callout-note}


### Communication  {{< fa bullhorn >}}

Material is available from  [s-v-b.github.io/MA7BY020](https://s-v-b.github.io/MA7BY020)

[Moodle](https://moodle.u-paris.fr/course/view.php?id=6143)

Subscribe to [Moodle portal](https://moodle.u-paris.fr/course/view.php?id=6143) 

:::

::: {.callout-note}

### [Software](/course-support.html) {{< fa bullhorn >}}


- [`R`](https://www.r-project.org)
- [`Posit`](https://posit.co)
- [`rstudio`](https://posit.co/products/open-source/rstudio/)
- [`quarto`](https://quarto.org)
- [`vs code`](https://code.visualstudio.com)
- [`git`](https://git-scm.com)
- [`docker`](https://www.docker.com)
- [`postgresql`](https://www.postgresql.org)

 
:::


::: {.callout-note}


## References  {{< fa book >}}

- Bin Yu and Rebecca Barter, [Veridical Data Science](https://vdsbook.com)
- Hadley Wickham, [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org)
- Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund, [R for Data Science](https://r4ds.hadley.nz)
- Hadley Wickham, [Advanced R](https://adv-r.hadley.nz)
- Hadley Wickham and Jennifer Bryan., [R packages](https://r-pkgs.org)
- Hadley Wickham, [Mastering Shiny](https://mastering-shiny.org)
- [`kaggle`](https://www.kaggle.com)
:::


::: {.callout-note}

### Course material  {{< fa chalkboard-teacher >}}

[Slides](/slides-listings.qmd) 

Labs are  [available](/labs-listings.qmd) (html and pdf)

Labs  with corrections are [available](/labs-solutions-listings.qmd)



:::

::: {.callout-important}

###  {{< fa graduation-cap >}}


- 3 projects:

   - $\textsf{P}_1$ Visualization
   - $\textsf{P}_2$ Regression
   - $\textsf{P}_3$ Packaging

- Grading

$$.2 \textsf{P}_1 + .3 \textsf{P}_2 + .5 \textsf{P}_3$$


:::




::: {.callout-warning}

### Code of conduct

**TL;DR: No cheating!**

:::



 

::: {.callout-important}


### Save the dates !  {{< fa calendar >}}

Click [here]() for [U Paris Cite]() Calendar.

Click [here](https://edt.math.univ-paris-diderot.fr/#/parcours/mathinfo/m1) for M1 MIDS Calendar

:::


::: {.callout-note}

## [Université Paris Cité](https://u-paris.fr)

Useful links:

- [Charte Université Paris Cité](https://u-paris.fr/valeurs/)
- [Démarches et accessibilité](https://u-paris.fr/demarches-administratives-de-scolarite/)
- [Centre de contact](https://u-paris.fr/centre-de-contact/)
- [Relais handicap](https://u-paris.fr/etudes-et-handicap/)

:::
