---
title: "Week 9"
subtitle: "SVD and Applications: Multiple Correspondence Analysis"
editor: source
draft: False
---

::: callout-important

-   Session I Sophie Germain (2017) Monday 16h-17h30
-   Session II Sophie Germain (2011) Friday 16h45-18h15
-   {{< fa cal >}} [Calendar](https://edt.math.univ-paris-diderot.fr/#/parcours/mathinfo/m1)

:::



::: {.callout-important}

### Very (very) important 

During session I (Monday 16th, afternoon), each team will have *5 minutes* to present their 
results from [Homework I](/core/projects/hmw_gapminder_oecd.qmd) and *5 minutes* to answer question(s). 

{{< fa hand-point-right >}} Each team will have to prepare one or two slides and a short pitch commenting the pictures. 

{{< fa hand-point-right >}} All team members must attend the defense and be prepared to answer questions. 


| Team  | Schedule |
|:-----|:-----------:|
| `ls-leon` | 16:00 |
| `LOR75` | 16:10  |
| `abdjin-xxx` | 16:20  |
| `Sidi-xxx` | 16:30  |
| `MA7BY020-2026` | 16:40  |
| `sabrina-xxxx` | 16:50  |
| `Steven-xxx` | 17:00  |
| `T1S2G3` | 17:10  |
| `aya-xxx` | 17:20  |
| `sevikri-xxx` | 17:30  |
| `OsKaR31415` | 17:40  |
| `yaniogl` | 17:50  |

Bring your laptop with a working HDMI connector 

## {{< fa display >}} {{< fa person-chalkboard >}}

:::

## {{< fa chalkboard-teacher >}} Blackboard

## {{< fa flask-vial >}} Labs

- [Lab 10](/core/labs/lab-mca.qmd)  Multiple Correspondence Analysis  as application of SVD


We still rely on the previous labs

- [Lab 1](/core/labs/lab-r-intro.html) - Introduction to R and RStudio
- [Lab 2](/core/labs/lab-gapminder.html) - Introduction to Data Visualization using Gapminder dataset
- [Lab 3](/core/labs/lab-tables.html) - Working with `dplyr`
- [Lab 4](/core/labs/lab-univariate-categorical.qmd) Univariate categorical variables
- [Lab 5](/core/labs/lab-univariate-numeric.qmd) Univariate numeric variables
- [Lab 6](/core/labs/lab-linear-regression-whiteside.qmd) - Linear Regression I
- [Lab 6](/core/labs/lab-linear-regression-whiteside-2.qmd) - Linear Regression II
- [Lab 7](/core/labs/lab-linear-regression-whiteside-2.qmd) - Linear Regression II
- [Lab 8](/core/labs/lab-pca.qmd)  Principal Component Analysis as an application of SVD
- [Lab 9](/core/labs/lab-ca.html)  Correspondence Analysis as an application of extended SVD

## {{< fa person-digging >}} Further work

{{< fa hand-point-right >}} Review the content of the two labs. Work out every part you do not already know. 
Report an issue if you are unhappy with the proposed solutions/hints.


## {{< fa book >}} Further reading

- Bin Yu and Rebecca Barter, [Veridical Data Science](https://vdsbook.com/06-pca)
- [`R` for data science](https://r4ds.hadley.nz)
- [Advanced `R`](https://adv-r.hadley.nz)
  - S3 classes
  - S4 classes
  
 
## {{< fa laptop >}} Logistics  

{{< fa bullhorn >}}{{< fa bullhorn >}} : you will work with the [`R` programming language](https://www.r-project.org) in this course. 

You need either to install `R`, `RStudio` and `VS Code` on your computer, or to use your `posit-cloud` account. 

{{< fa bullhorn >}}{{< fa bullhorn >}} Install [`Quarto`](https://quarto.org) on your computer to render the `.qmd` files. 

Please follow the instructions [here](/computing-access.qmd) to install `R`, `RStudio`, `VS Code`, and `Quarto` or to access `posit-cloud`. 

{{< fa bullhorn >}}{{< fa bullhorn >}} Please activate your ENT account (follow the instructions on [Moodle](https://moodle.u-paris.fr/course/view.php?id=6143)). You will be able to access the PostGres server.


<br><br>

::: {style="font-size: 0.875em;"}
Back to [Agenda](/slides-listings.qmd) ⏎
:::
