---
title: "Week 7"
subtitle: "Linear Regression (continued)"
editor: source
draft: true
---

::: callout-important

-   Session I Sophie Germain (2017) Monday 16h-17h30
-   Session II Sophie Germain (2011) Friday 16h45-18h15
-   {{< fa cal >}} [Calendar](https://edt.math.univ-paris-diderot.fr/#/parcours/mathinfo/m1)

:::

## {{< fa chalkboard-teacher >}} Blackboard

- Ordinary Least Squares
- QR factorizatio
- Ridge regression (Regularized Least Squares)
- Pseudo-Inversion
- Linear regrssion with `R`  

## {{< fa flask-vial >}} Labs

- [Lab 6](/core/labs/lab-linear-regression-whiteside.qmd) - Linear Regression I
- [Lab 7](/core/labs/lab-linear-regression-whiteside-2.qmd) - Linear Regression II  
<!-- - [Lab 8](/core/labs/lab-prog-R.qmd) - Aspects of Programming with `R` --> -->

We still rely on the previous labs

- [Lab 1](/core/labs/lab-r-intro.html) - Introduction to R and RStudio
- [Lab 2](/core/labs/lab-gapminder.html) - Introduction to Data Visualization using Gapminder dataset
- [Lab 3](/core/labs/lab-tables.html) - Working with `dplyr`
- [Lab 4](/core/labs/lab-univariate-categorical.qmd) Univariate categorical variables
- [Lab 5](/core/labs/lab-univariate-numeric.qmd) Univariate numeric variables


## {{< fa person-digging >}} Further work

{{< fa hand-point-right >}} Review the content of the two labs. Work out every part you do not already know. 
Report an issue if you are unhappy with the proposed solutions/hints.


## {{< fa book >}} Further reading

- Bin Yu and Rebecca Barter, [Veridical Data Science](https://vdsbook.com/05-data_viz)
- [`R` for data science](https://r4ds.hadley.nz)
- [Advanced `R`](https://adv-r.hadley.nz)
  - S3 classes
  - S4 classes
- [Cours de Statistique Fondamentale](https://statsfonda.github.io/site/)
  - [Modèles linéaires](https://statsfonda.github.io/site/content/ch5_01.html)
  - [Sherman–Morrison–Woodbury formula](https://statsfonda.github.io/site/content/app3.html#inversion-des-perturbations-de-rang-faible)
- [Sourav Chatterjee: A new correlation coefficient](https://arxiv.org/abs/1909.10140)  
 
## {{< fa laptop >}} Logistics  

{{< fa bullhorn >}}{{< fa bullhorn >}} : you will work with the [`R` programming language](https://www.r-project.org) in this course. 

You need either to install `R`, `RStudio` and `VS Code` on your computer, or to use your `posit-cloud` account. 

{{< fa bullhorn >}}{{< fa bullhorn >}} Install [`Quarto`](https://quarto.org) on your computer to render the `.qmd` files. 

Please follow the instructions [here](/computing-access.qmd) to install `R`, `RStudio`, `VS Code`, and `Quarto` or to access `posit-cloud`. 

{{< fa bullhorn >}}{{< fa bullhorn >}} Please activate your ENT account (follow the instructions on [Moodle](https://moodle.u-paris.fr/course/view.php?id=6143)). You will be able to access the PostGres server.


<br><br>

::: {style="font-size: 0.875em;"}
Back to [Agenda](/slides-listings.qmd) ⏎
:::
